apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-service
spec:
  selector:
    app: test-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: 30080
