apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-service22
spec:
  selector:
    app: test-app2
  type: NodePort
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 80
