apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-service
spec:
  selector:
    app: test-app2
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
